name: Test and Lint

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - run: npm install
      - run: npm run build
      - run: npm run lint:ci
      - run: npm run test:ci
